ISSITES-5938 clean up mobile styling for learn site
willnewbury/liferay-portal pull request #143
Opened 2023-01-25 17:57 UTC by liaoethan

2023-01-25 17:57 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-01-31 18:28 UTC, allen-ziegenfus requested changes

2023-01-31 18:28 UTC, allen-ziegenfus commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-theme-css/src/css/_documentations.scss
> +			color: var(--color-action-neutral-default);
use the sass variable here

2023-01-31 18:28 UTC, allen-ziegenfus commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-theme-css/src/css/_landing_page.scss
> +		display: contents;
we can also achieve that with flex: 100%

2023-01-31 18:28 UTC, allen-ziegenfus commented on workspaces/liferay-learn-workspace/client-extensions/liferay-learn-theme-css/src/css/_landing_page.scss
> +		border: 1px solid var(--color-neutral-3);
use sass variable

2023-02-02 21:19 UTC, allen-ziegenfus commented
@liaoethan 

I'm a little confused by this PR - it looks like you have mixed in commits for the public site nav that were already merged into the learn branch but here they are causing merge conflicts.

Please create a new PR and send it to me on the `learn` branch rather than master

Also it's not clear to me whether we need the arrows are not on landing pages - I noticed you changed the color to black on the h4 links, but that doesn't match what I see on the mockups.

2023-02-06 16:20 UTC, liaoethan commented
Hey @allen-ziegenfus, I recreated the pull here and took out the changes (landing page arrows) that didn't affect the mobile styling:
https://github.com/allen-ziegenfus/liferay-portal/pull/92

2023-02-06 16:20 UTC, closed without merging